- name: create application directory
  file:
    path: /opt/bin/admin
    state: directory
    mode: 0777
  become: true

- name: create application tmp directory
  file:
    path: /opt/bin/admin/tmp
    state: directory
    mode: 0777
  become: true