- name: template - admin.sh
  template:
    src: templates/admin.sh.j2
    dest: /opt/bin/admin/admin.sh
    mode: 0755

- name: template - config.groovy
  template:
    src: templates/config.groovy.j2
    dest: /opt/bin/admin/config.groovy
  when: legacy == false