- name: set variables
  run_once: true
  set_fact:
    app_templates: ["lendingservices", "lp", "crm", "portal", "admin", "hydra", "lom", "sfa", "hip", "shuttle"]

- name: Update apt
  shell: sudo apt update

- name: Install packages
  expect:
    command: sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
    responses:
      "Do you want to continue?": "Y"

- name: install and enable nginx
  import_tasks: install_enable.yml

- name: install and enable nginx
  import_tasks: push_global_config.yml

- name: push config files
  include_tasks: push_config.yml
  vars:
    port: "{{ item }}"
  loop: "{{ nginx.keys() | list }}"

- name: create ssl file
  include_tasks: create_ssl.yml
  vars:
    port: "{{ item }}"
  loop: "{{ nginx.keys() | list }}"

- name: restart nginx
  service: 
    name: nginx
    state: restarted
    enabled: yes
