- name: template - app-locations files
  template:
    src: "templates/{{ app_template }}-locations.j2"
    dest: /etc/nginx/{{ app_template }}-locations
  when: app_template in app_templates
  loop: "{{ nginx[port].nginx_apps }}"
  loop_control:
    loop_var: app_template
  become: true