---
- name: Setup Servers
  hosts: all
  gather_facts: no
  vars:
    client: "{{ inventory_hostname.split('_')[0] }}"
    env: "{{ inventory_hostname.split('_')[1] }}"
    apps: "{{ hostvars[inventory_hostname].apps }}"

  tasks:
    - name: Update apt
      shell: sudo apt update

    # run once?
    - name: Install packages
      expect:
        command: sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
        responses:
          "Do you want to continue?": "Y"

    # should this be a role?
    - name: Set .aws/config
      include_tasks: tasks/aws_config.yml

    - name: Run cloudwatch tasks
      include_role:
        name: cloudwatch

    # should this be a role?
    - name: Set vim config
      include_tasks: tasks/vim.yml
            
    - name: Run nginx tasks
      include_role:
        name: nginx

    ## NEWRELIC ##

    - name: Run applications tasks
      include_role:
        name: "app_{{ item }}"
      # when: item in ["lendingservices", "lp", "crm", "portal", "admin", "hydra", "hip", "lom"]
      when: item in ["lendingservices"]
      loop: "{{ apps }}"

    - name: restart nginx
      service: 
        name: nginx
        state: restarted
        enabled: yes
      become: yes      

    - name: restart apps
      shell: |
        systemctl restart {{ item }}.service
      loop: "{{ apps }}"
      when: item in ["lendingservices", "lp", "crm", "portal", "admin", "hydra", "lom"]
      become: yes
