---
- name: Setup Servers
  hosts: all
  gather_facts: no
  vars:
    client: "{{ inventory_hostname.split('_')[0] }}"
    env: "{{ inventory_hostname.split('_')[1] }}"
    apps: "{{ hostvars[inventory_hostname].apps }}"
    bss_devops_aws_profile: "it-devops-bss-devops"

  tasks:
    # should this be a role?
    - name: Set .aws/config
      include_tasks: tasks/aws_config.yml

    - name: Run cloudwatch tasks
      include_role:
        name: cloudwatch

    # should this be a role?
    - name: Set vim config
      include_tasks: tasks/vim.yml
            
    - name: Run nginx tasks
      include_role:
        name: nginx

    - name: Run applications tasks
      include_role:
        name: "app_{{ item }}"
      when: item in ["lendingservices", "lp", "crm", "portal", "admin", "hydra", "hip", "lom", "shuttle"]
      loop: "{{ apps }}"

    - name: restart nginx
      service: 
        name: nginx
        state: restarted
        enabled: yes
      become: yes      

    - name: restart apps
      shell: |
        systemctl restart {{ item }}.service
      loop: "{{ apps }}"
      when: item in ["lendingservices", "lp", "crm", "portal", "admin", "hydra", "lom", "shuttle"]
      become: yes

    # - name: Install new relic agent
    #   include_role:
    #     name: install_newrelic_java_agent