---
- name: Setup Servers
  hosts: all
  gather_facts: no
  vars:
    client: "{{ inventory_hostname.split('_')[0] }}"
    env: "{{ inventory_hostname.split('_')[1] }}"
    apps: "{{ hostvars[inventory_hostname].apps }}"

  tasks:
    - name: Update apt
      shell: sudo apt update

    - name: Install packages
      expect:
        command: sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring
        responses:
          "Do you want to continue?": "Y"
    
    # - name: Nginx
    #   include_role:
    #     name: nginx