- name: create directories
  import_tasks: create_dirs.yml

- name: install java 11
  shell: |
    apt update -y
    add-apt-repository ppa:openjdk-r/ppa -y
    apt install openjdk-11-jdk-headless -y 
  become: yes

# main files are uploaded unless {files} is provided at a higher level
- name: upload shuttle files 
  import_tasks: ../../../tasks/upload_files.yml
  vars:
    files:
      shuttle.service: /lib/systemd/system/
      shuttle.sh: /opt/bin/shuttle/
  become: true

- name: give permissions to startup file
  file:
    path: /opt/bin/shuttle/shuttle.sh
    mode: 0755
  become: true

# - name: get database data
#   import_tasks: ../../../tasks/get_db_data.yml

# - name: push config files
#   import_tasks: push_config.yml

