- name: define lower envs
  set_fact:
    lower_envs:
      - dev
      - qa
      - uat
      - stg
      - prodmirror
      - sit

- name: set env for ssm
  set_fact:
    ssm_env: "{{ 'lower' if env in lower_envs else env }}"

- name: get shuttle credentials secret
  set_fact:
    shuttle_secret: "{{ lookup('amazon.aws.aws_secret', '/dbconfig/' + ssm_env + '/' + client + '-' + ssm_env + '-shuttle-aws-credentials', aws_profile=aws_profile) }}"

- name: get shuttle credentials
  set_fact:
    shuttle_access_key: "{{ shuttle_secret.access_key }}"
    shuttle_secret_key: "{{ shuttle_secret.secret_key }}"

- name: template - application.yml
  vars: 
    cluster_path: "{{ database.hostname | replace('cluster-', 'cluster-ro-') }}"
  template:
    src: templates/application.yml.j2
    dest: /opt/bin/shuttle/application.yml
  when: env not in ["dev"]

- name: template - application.yml
  vars: 
    cluster_path: "{{ database.hostname }}"
  template:
    src: templates/application.yml.j2
    dest: /opt/bin/shuttle/application.yml
  when: env in ["dev"]