- name: install aws cli v2
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  args:
    creates: /usr/local/aws-cli/v2/current/bin/aws