- name: set ssm_map to search ssm params
  set_fact:
    ssm_map:
      homebridge: hb
      kindretail: kindr
      lendage: lend
      mfmcorr: mfmc
      springeq: seq
      springeqfirst: seqf
      westerra: west

- name: set ssm_client
  set_fact:
    ssm_client: "{{ ssm_map[client] if client in ssm_map.keys() | list else client }}"

- name: get jwt token
  set_fact:
    jwt_token: "{{ lookup('amazon.aws.aws_ssm', '/secrets/' + ssm_client + '/' + env + '/' + app + '/' + 'jwt-password', aws_profile=bss_devops_aws_profile) }}"

- name: add line to config.groovy
  lineinfile:
    path: "{{ '/opt/bin/' + app + '/config.groovy' }}"
    line: "{{ 'grails.plugin.springsecurity.rest.token.storage.jwt.secret=' + '\"' + jwt_token + '\"' }}"
    backup: true
    # state: absent