- name: upload files
  vars:
    files_dicts: "{{ files | dict2items(key_name='file', value_name='path') }}"
  copy:
    src: "{{ file_dict.file }}"
    dest: "{{ file_dict.path }}"
  loop: "{{ files_dicts }}"
  loop_control:
    loop_var: file_dict