- name: Get New Relic Service Account Key
  delegate_to: localhost
  run_once: true
  shell: |
    API_KEY=$(aws ssm get-parameter --name /secrets/new_relic/api_key --with-decryption --query "Parameter.Value" --output text)

    if [ -z "$API_KEY" ]; then
      echo Unable to read api key, are you logged in and able to read from bss account?
      exit 1
    fi

    echo $API_KEY
  register: api_key
- name: Set Api Key as Fact
  run_once: true
  set_fact:
    api_key: "{{ api_key.stdout }}"

- name: update_client_group_permissions
  run_once: true
  import_tasks: update_client_group_permissions.yml
- name: get_license_key
  run_once: true
  import_tasks: get_license_key.yml
- name: install_newrelic_java_agent
  import_tasks: install_newrelic_java_agent.yml