- name: Set Variables
  delegate_to: localhost
  run_once: true
  set_fact:
    authentication_domain_id: 0f4dda55-888e-4f4d-abba-ac7b3417faba
    read_only_role_id: 1252

- name: Query New Relic Groups
  delegate_to: localhost
  run_once: true
  shell: |
    QUERY_GROUP_RESPONSE=$(curl https://api.newrelic.com/graphql \
      -H 'Content-Type: application/json' \
      -H 'API-Key: {{api_key}}' \
      --data-binary '{
                      "query": "{actor {organization {userManagement {authenticationDomains(id: \"{{ authentication_domain_id }}\") {authenticationDomains {groups {groups {displayName id users {users {name id}}}}}}}}}}",
                      "variables": ""
                    }'
    )
    CLIENT_GROUP_ID=$(echo $QUERY_GROUP_RESPONSE | jq -r '.data.actor.organization.userManagement.authenticationDomains.authenticationDomains.[0].groups.groups.[] | select(.displayName == "{{client}}Readonly") | .id')
    echo $CLIENT_GROUP_ID
  register: client_group_id

- name: Set Client Group ID as Fact
  delegate_to: localhost
  run_once: true
  set_fact:
    client_group_id: "{{ client_group_id.stdout }}"

- name: Query Accounts
  delegate_to: localhost
  run_once: true
  shell: |
    QUERY_ACCOUNT_RESPONSE=$(curl https://api.newrelic.com/graphql \
      -H 'Content-Type: application/json' \
      -H 'API-Key: {{api_key}}' \
      --data-binary '{
                        "query": "{actor {organization {accountManagement {managedAccounts(isCanceled: false) {name id}}}}}",
                        "variables": ""
                    }'
    )

    CLIENT_ACCOUNT_ID=$(echo $QUERY_ACCOUNT_RESPONSE | jq '.data.actor.organization.accountManagement.managedAccounts.[] | select(.name == "{{client}}") | .id')

    echo $CLIENT_ACCOUNT_ID

  register: client_account_id

- name: Set Account Id as Fact
  set_fact:
    client_account_id: "{{ client_account_id.stdout }}"


- name: Update client read only group Permissions
  delegate_to: localhost
  run_once: true
  shell: |
    UPDATE_PERMISSIONS_RESPONSE=$(curl https://api.newrelic.com/graphql \
      -H 'Content-Type: application/json' \
      -H 'API-Key: {{api_key}}' \
      --data-binary '{
                        "query": "mutation {authorizationManagementGrantAccess(grantAccessOptions: {groupId: \"{{client_group_id}}\" accountAccessGrants: {accountId: {{client_account_id}} roleId: \"{{read_only_role_id}}\"}}) {roles {displayName accountId}}}",
                        "variables": ""
                    }'
    )