- name: create application directory
  file:
    path: /opt/bin/portal
    state: directory
    mode: 0777
  become: true

- name: create application tmp directory
  file:
    path: /opt/bin/portal/tmp
    state: directory
    mode: 0777
  become: true

- name: create rules-backups directory
  file:
    path: /home/ubuntu/rules-backups
    state: directory