- name: clone deploy-scripts repos
  git:
    repo: git@github.com:BlueSageSolutions/deploy-scripts.git
    dest: /home/ubuntu/deploy
    accept_newhostkey: true

- name: clone DBMigration repos
  git:
    repo: git@github.com:BlueSageSolutions/DBMigration.git
    dest: /home/ubuntu/DBMigration
    accept_newhostkey: true

- name: create dirs in deploy/
  file:
    path: /home/ubuntu/deploy/{{ item }}
    state: directory
  loop:
    - artifacts
    - app-backups
    - rules-backups