- name: setup_prod_ssh
  import_tasks: ssh.yml

- name: setup_prod_config_flags
  import_tasks: config_flags.yml

- name: install_aws_cli_v2
  import_tasks: ../../../tasks/install_aws_cli_v2.yml

- name: install_jq
  import_tasks: ../../../tasks/install_jq.yml

- name: install_mysql
  import_tasks: ../../../tasks/install_mysql.yml
  when: controller

- name: ensure correct java version selected
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/zulu-7-amd64/jre/bin/java
  when: controller
  become: true

- debug:
    msg: "{{ pub_key.stdout }}"
  run_once: true

#TODO: need a wait here for someone to add the pub_key to GitHub

- name: Prompt for confirmation
  pause:
    prompt: "Add public key from debug output to github (https://github.com/settings/keys). You must be logged in as BlueSage Builder. \nPress Enter when completed"

- name: setup git repos
  import_tasks: git.yml
  when: controller
  tags:
    - git