- name: Copy AWS keypair to LOS-A instance
  copy:
    src: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}"
    dest: "/home/ubuntu/.ssh/{{ aws_key }}"
  when: controller

- name: Change permissions on AWS keypair
  file:
    path: "/home/ubuntu/.ssh/{{ aws_key }}"
    mode: "600"
    owner: ubuntu
  when: controller

- name: Generate ssh key on LOS-A instance
  community.crypto.openssh_keypair:
    path: /home/ubuntu/.ssh/id_rsa
    comment: "{{ client|upper }}_PROD_APPS"
    backend: opensshbin
    owner: ubuntu
  when: controller

- name: Ensure servers are present in known_hosts file
  known_hosts:
    name: "{{ hostvars[item].ansible_host }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
    # hash_host: true
  loop: "{{ groups[group] }}"
  when: controller and item != inventory_hostname

- name: Copy public key to all other instances from LOS-A
  shell: |
    scp -i /home/ubuntu/.ssh/{{ aws_key }} /home/ubuntu/.ssh/id_rsa.pub ubuntu@{{ hostvars[item].ansible_host }}:/home/ubuntu/.ssh/
  loop: "{{ groups[group] }}"
  when: controller and item != inventory_hostname

- name: Register public key
  run_once: true
  shell: |
    cat .ssh/id_rsa.pub
  register: pub_key

- name: Ensure public key is in authorized_keys file on all instances
  lineinfile:
    path: /home/ubuntu/.ssh/authorized_keys
    line: "{{ pub_key.stdout }}"
    state: present

- name: Remove public key on all non LOS-A instances
  shell: |
    rm .ssh/id_rsa.pub
  when: controller == False

- name: Set fact to create .ssh/config file on LOS-A instance
  set_fact:
    ssh_lines: "{{ ssh_lines | default([])
      + ['Host ' + item | replace('_', '-') ]
      + ['        Hostname ' + hostvars[item].ansible_host ]
      }}"
  loop: "{{ groups[group] }}"
  when: controller

- name: Create .ssh/config file on LOS-A
  lineinfile:
    path: /home/ubuntu/.ssh/config
    line: "{{ item }}"
    state: present
    create: true
  loop: "{{ ssh_lines }}"
  when: controller

- name: Remove AWS keypair from LOS-A instance
  shell: |
    rm .ssh/{{ aws_key }}
  when: controller