- name: template - lp.sh
  template:
    src: templates/lp.sh.j2
    dest: /opt/bin/lp/lp.sh
    mode: 0755

- name: template - config.groovy
  template:
    src: templates/config.groovy.j2
    dest: /opt/bin/lp/config.groovy
  when: legacy == false

- name: custom timezone - config.groovy
  lineinfile:
    path: /opt/bin/lp/config.groovy
    line: "{{ item.line }}"
  loop:
    - line: "\n"
    - line: dateTime.displayTimeZone = "{{ config_groovy_timezone }}"
    - line: dateTime.pricingTimeZone = "{{ config_groovy_timezone }}"
  when: config_groovy_timezone is defined and legacy == false