---
- name: Setup Servers
  hosts: all
  gather_facts: no
  vars:
    client: "{{ inventory_hostname.split('_')[0] }}"
    env: "{{ inventory_hostname.split('_')[1] }}"
    apps: "{{ hostvars[inventory_hostname].apps }}"
    # bss_devops_aws_profile: "sso-devops-bss-devops"
    group: "{{ client }}_{{ env }}"
    aws_key: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file.split('/')[-1] }}"
    controller: "{{ hostvars[inventory_hostname].controller | default(False) }}"
    disable_batch: "{{ hostvars[inventory_hostname].disable_batch | default(False) }}"
    disable_pwd_encode: "{{ hostvars[inventory_hostname].disable_pwd_encode | default(False) }}"

  vars_prompt:
    - name: bss_devops_aws_profile
      prompt: What is your devops aws profile?
      private: false

  tasks:
    # should this be a role?
    - name: Set .aws/config
      include_tasks: 
        file: ../../tasks/aws_config.yml
        apply:
          tags: always
      tags: always


    - name: Run cloudwatch tasks
      include_role:
        name: cloudwatch
        apply:
          tags: always
          become: yes
      tags: always

    # should this be a role?
    - name: Set vim config
      include_tasks:
        file: ../../tasks/vim.yml
        apply:
          tags: always
      tags: always
  
    - name: Run nginx tasks
      include_role:
        name: nginx
        apply:
          tags: [always, nginx]
          become: yes
      tags: [always, nginx]

    - name: Run applications tasks
      include_role:
        name: "app_{{ item }}"
        apply:
          tags: always
          become: yes
      when: item in ["lendingservices", "lp", "crm", "portal", "admin", "lom", "hydra", "lion", "sfa", "hip", "shuttle", "servicing"]
      loop: "{{ apps }}"
      tags: always

    - name: Install new relic agent
      include_role:
        name: install_newrelic_agent
        apply:
          tags: [prod, newrelic]
      loop: "{{ apps }}"
      when: item in ["lendingservices", "lp", "crm", "portal", "admin", "servicing"]
      vars: 
        aws_profile: "{{ bss_devops_aws_profile }}"
      tags: [never, prod, newrelic]

    - name: Setup Prod Servers
      include_role:
        name: server_prod
        apply:
          tags: [prod]
      tags: [never, prod, git]

    - name: restart nginx
      service: 
        name: nginx
        state: restarted
        enabled: yes
      become: yes
      tags: [never, restart]

    - name: restart apps
      shell: |
        systemctl restart {{ item }}.service
      loop: "{{ apps }}"
      when: item in ["lendingservices", "lp", "crm", "portal", "admin", "hydra", "lom", "shuttle"]
      become: yes
      tags: [never, restart]