---
- name: Change Timezone
  hosts: all
  gather_facts: no
  vars:
    client: "{{ inventory_hostname.split('_')[0] }}"
    env: "{{ inventory_hostname.split('_')[1] }}"
    apps: "{{ hostvars[inventory_hostname].apps }}"
  tasks:
    - name: Set Variables
      run_once: true
      set_fact:
        shuttle_jar_name: shuttleApp_0.52.34.jar
        downloads_dir: ../../downloads

    - name: Download shuttle jar from s3
      delegate_to: localhost
      run_once: true
      shell: |
        aws s3api get-object --bucket bss-application-management --key {{ shuttle_jar_name }} {{ downloads_dir }}/{{ shuttle_jar_name }}