- name: Update apt
  shell: sudo apt update

- name: Install OpenJDK 21
  apt:
    name: openjdk-21-jdk
    state: present

- name: ensure correct java version selected
  alternatives:
    name: java
    path: /usr/lib/jvm/java-21-openjdk-amd64/bin/java

- name: create servicing subdirectory
  file:
    path: /opt/bin/servicing/config
    state: directory
    mode: 0777

- name: upload servicing files 
  import_tasks: ../../../tasks/upload_files.yml
  vars:
    files:
      servicing.service: /lib/systemd/system/
  become: true

- name: get app user creds
  set_fact:
    app_user: "{{ lookup('amazon.aws.aws_secret', 'servicing-app-user-' + env + '-' + 'aws-credentials', aws_profile=aws_profile) }}"

- name: get app user keys
  set_fact:
    app_user_access_key: "{{ app_user.access_key }}"
    app_user_secret_key: "{{ app_user.secret_key }}"

- name: template - servicing.sh
  template:
    src: templates/servicing.sh.j2
    dest: /opt/bin/servicing/servicing.sh

- name: give permissions to startup file
  file:
    path: /opt/bin/servicing/servicing.sh
    mode: 0755
  become: true